audit_header: false
title: Mastermind Blog
description: A private learning club real estate agent teams and rainmakers.
show_custom_links: true
custom_links:
  - title: Free Goal Setting Call
    url: https://www.getvyral.com/free-marketing-strategy-call
  - title: Subscribe to Our Podcast
    url: /

client:
  name: Sara Wodrich
  title:
  license_number:
  about_markdown: |
    The Mastermind of Entrepreneurial Real Estate Agents Who Share Their 7-and-8 Figure Plans and Strategies...So You Too Can Grow Your Business with Ease In a Way That Makes You Happy. A Private Learning Club of America's Most Successful Real Estate Agent Teams and Rainmakers.

    "If You've Reached a Plateau, You're Missing a Person" - Gary Keller
  brand: Mastermind Club
  brokerage:
  market:
  address: 406 9th Ave Suite 204 San Diego Ca. 92101
  phone: 402.281.2924
  phone_type:
  phone2:
  phone2_type:
  email: sara@mastermindclub.us
  url: http://www.mastermindclub.us

CTAs:
  first_CTA_text: Free Goal Setting Call
  first_CTA_URL: https://www.getvyral.com/free-marketing-strategy-call
  second_CTA_text: Subscribe to Our Podcast
  second_CTA_URL: /

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Career?"
    CTA_text: "Let's talk about how we can take your business to new heights."
    CTA_link_text: "Free Goal Setting Call"
    CTA_url: https://www.getvyral.com/free-marketing-strategy-call

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Get Insider Information"
    CTA_text2: "Listen + Learn."
    CTA_link_text2: "Subscribe to Our Podcast"
    CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: http://www.facebook.com/VyralMarketing
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.JPG
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#56232d'
  theme_color: '#000000'
  accent_color: '#FFA801'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
